### ISSUE TITLE
Cant change the Language of the Game

### ISSUE THREAD

**Issue by EntchenEric** [Tom-the-Bomb/akinator.py#10]
If you start a Game using `akinator.Akinator(theme=akinator.Theme.Characters, language=akinator.Language.German, child_mode=True)` the Language is still English and not German (same for the async version)

**Comment by Tom-the-Bomb** [comment]
@kollhdxdlp should be fixed now, update and try again and let me know.

**Comment by EntchenEric** [comment]
Works, Thank you 👍
