### ISSUE TITLE
getting error in whan execute akinator command in discord.py

### ISSUE THREAD

**Issue by ankushomg** [Tom-the-Bomb/akinator.py#11]
RuntimeError: RequestError: error sending request for url (https://en.akinator.com/): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

**Comment by Tom-the-Bomb** [comment]
I've taken a look and it seems that that error is due to the fact that the library deems that the akinator.com SSL certificate is invalid.

I'm not sure how to fix it or even if it is my issue at all, as it has been reproduced across many libraries and devices.

I'll continue to take a look but for now I can also just disable SSL verification to make it work but its kind of scuffy and risky.

So in short it technically should work.. update and let me know

**Comment by ankushomg** [comment]
after update akinator.py version to 0.2.4..getting this error
RuntimeError: RequestError: error following redirect for url (https://en.akinator.mobi/): too many redirects

can you tell me,this error is from my side or this is the api issue.

**Comment by Tom-the-Bomb** [comment]
I cannot reproduce that error on my machine whatsoever, unfortunately.

what is your code?

**Comment by ankushomg** [comment]
https://pastebin.com/skx9S8gu here you go,and please correct it for me,and after that also tell to me that where i was wrong

**Comment by Tom-the-Bomb** [comment]
Yes, but I also need the full error + traceback so I can see what caused it.

Additionally, just to make sure it is a (your code) issue do you mind running one of my scripts such as one of the [tests](https://github.com/Tom-the-Bomb/akinator.py/tree/master/tests) or by using my [discord-games](https://github.com/Tom-the-Bomb/Discord-Games) library's akinator instead.

**Comment by ankushomg** [comment]
```py
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/cogs/commands/List.py", line 17, in akinator
    question = await akinator_game.start_game()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: RequestError: error following redirect for url (https://en.akinator.mobi/): too many redirects

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/jishaku/features/invocation.py", line 168, in jsk_debug
    await alt_ctx.command.invoke(alt_ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: RequestError: error following redirect for url (https://en.akinator.mobi/): too many redirects

```

**Comment by ankushomg** [comment]
and your discord-game module also giving this error RuntimeError: RequestError: error following redirect for url (https://en.akinator.mobi/): too many redirects

**Comment by Tom-the-Bomb** [comment]
![image](https://user-images.githubusercontent.com/77308095/235480013-4799a751-92ad-4bb5-bc20-f1cc3413d00f.png)

It works for me, try running just that, but my guess is that it still won't work.

Are you sure you are updated? It also could be that you are on 3.11 but I am on 3.10, try it on 3.10 if you could,
but I will also try on 3.11.

**Comment by ankushomg** [comment]
![Screenshot_2023-05-01-21-19-22-471_com discord](https://user-images.githubusercontent.com/79055580/235481456-622fdf7a-3b7a-45a4-b787-b1ab06c2d091.jpg)
btw, I'm using python version 3.11 and 3.9

**Comment by ankushomg** [comment]
can i get your discord server link?

**Comment by ankushomg** [comment]
![Screenshot_2023-05-01-21-34-40-016_com discord](https://user-images.githubusercontent.com/79055580/235484065-5abe3b1b-d2c7-479c-8457-926fb96adbb4.jpg)

![Screenshot_2023-05-01-21-34-50-431_com discord](https://user-images.githubusercontent.com/79055580/235484092-c5df7427-347f-45e5-985c-7a5dcfcc246f.jpg)
  
![Screenshot_2023-05-01-21-36-13-814_com discord](https://user-images.githubusercontent.com/79055580/235484295-ec1f689f-cc97-4b61-b8f4-1ce4d681051d.jpg)


see this, I also used 3.10 and my version is updated of akinator.py

**Comment by ankushomg** [comment]
and it's not happening for me only, it's happening for all who used akinator.py or discord_games module in their bot..

**Comment by Tom-the-Bomb** [comment]
got it, I'll take a look and could be just something different with 3.11

**Comment by ankushomg** [comment]
sir make it so it's also work in 3.9,3.10 and 3.11 if possible..
and give me your discord server link please

**Comment by Tom-the-Bomb** [comment]
I just thought about it more and either way the python version should not affect it as underneath its all the rust doing the work and that's a rust error, anyways I did try it with 3.9-.11 and it all worked for me, including using the rust implementation directly too, on 2 separate machines, so I'm also at a loss regarding the issue...

**Comment by ankushomg** [comment]
sir, find any solution to fix it, because,many users facing this problem:)

**Comment by Tom-the-Bomb** [comment]
Again, I can't reproduce the error, I've even tried running the code in the cloud on repl.it and it worked there

so I'm unsure of how your machine is different or whoever these many users you are referring to that are also experiencing this error.

I'll ask around and look into it but right now I can't do much, if possible try using the rust implementation if you can, that will be more helpful for sure, but without more information I can't do much now.
