### ISSUE TITLE
Error when multiple users use the akinator command [async]

### ISSUE THREAD

**Issue by RayyanW786** [Tom-the-Bomb/akinator.py#13]
Result: Akinator game errored out:
`Failed to parse JSON: expected value at line 1 column 1`

code: 
async def answer(self, message: str, interaction: discord.Interaction):
        try:
            await self.aki.answer(Answer.from_str(message)) 
        except NoMoreQuestions:
            await self.win(interaction)
        except TimeoutError:
            await self.cancel("The connection to the Akinator servers was lost.")
        except Exception as error:
            await self.edit_or_send(
                interaction, content=f"Akinator game errored out:\n`{error}`", embed=None
            )
            self.stop()

Expected result: should work fine when two different games are started.

also I would like to take this opportunity to suggest if you could use aiohttp sessions and also allow us to pass our own session into the AsyncAkinator class

**Comment by RayyanW786** [comment]
Oh wait after further testing it seems the issue is gone and isn’t reproducible anymore now weird

**Comment by Tom-the-Bomb** [comment]
At the end of the day, this thing just uses it's non-public API so it definitely will be janky sometimes, likely not a library issue... (at least not that I am aware of)
