### ISSUE TITLE
Language.from_str doesn't support German

### ISSUE THREAD

**Issue by Soheab** [Tom-the-Bomb/akinator.py#16]
`akinator.Language.from_str` throws the following when "de" or "german" is passed to it:
```py
akinator.InvalidLanguage: Invalid language string
```

I don't know how this all works but believe this is an issue on the rust part of the wrapper, the following code has a line for all languages except German:
https://github.com/Tom-the-Bomb/akinator-rs/blob/89d53cc7f0add8d8710e58dd8d8c0a5482f3a0ed/src/enums.rs#L181-L201

**Comment by Tom-the-Bomb** [comment]
yea you're right, somehow I missed that, the `German` variant is still defined its just you canted do `from_str` to parse from str but `Language.GERMAN` still works for example.

However I will fix it as soon as possible.

**Comment by Tom-the-Bomb** [comment]
(I believe it should be fixed now?)
