### ISSUE TITLE
`ValueError: Failed to parse JSON: expected value at line 1 column 1`

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [Tom-the-Bomb/akinator.py#8]
I am getting this error when trying to use it with `disnake` a `discord.py` alternative.
`ValueError: Failed to parse JSON: expected value at line 1 column 1`

**Comment by Tom-the-Bomb** [comment]
Hello, please provide the entire traceback and your code, thanks

**Comment by Tom-the-Bomb** [comment]
Hello, do you still have this problem or was it resolved?

**Comment by Jonak-Adipta-Kalita** [comment]
> Hello, do you still have this problem or was it resolved?

Sorry I was busy coz of my Exams, I have solved the issue, I  just used AsyncAkinnator, but the issue in Akinator might be still there

**Comment by Tom-the-Bomb** [comment]
got it, no problem. Could you still post the full error/traceback you got and the code you used, if possible?

thanks
