### ISSUE TITLE
Failed to parse JSON: expected value at line 1 column 1

### ISSUE THREAD

**Issue by EntchenEric** [Tom-the-Bomb/akinator.py#9]
Whenever I attempt to start the game by using `aki.start_game()`, I receive the following error message: `Failed to parse JSON: expected value at line 1 column 1`. This issue also persists when running the tests provided in this repository.

The complete error message is as follows:
```
Exception has occurred: ValueError
Failed to parse JSON: expected value at line 1 column 1
  File "H:\Sayoka\extensions\tmp.py", line 17, in test
    first_question = aki.start_game()
                     ^^^^^^^^^^^^^^^^
  File "H:\Sayoka\extensions\tmp.py", line 53, in <module>
    test()
ValueError: Failed to parse JSON: expected value at line 1 column 1
```
(This error occurs when running the test_sync.py file available in the [akinator.py](https://github.com/Tom-the-Bomb/akinator.py/blob/master/tests/test_sync.py) repository.)

**Comment by Tom-the-Bomb** [comment]
ah, this is the 2nd time that has happened, it definitely worked before so I feel its an API issue, I will take a look.

**Comment by Tom-the-Bomb** [comment]
@kollhdxdlp and also @Jonak-Adipta-Kalita, fixed that issue, it was a regex problem, it worked before I do not know why it stopped working now, but it should work now.

Update to newest version on PYPI (v0.2.2) and try again, thanks!

**Comment by Jonak-Adipta-Kalita** [comment]
> @kollhdxdlp and also @Jonak-Adipta-Kalita, fixed that issue, it was a regex problem, it worked before I do not know why it stopped working now, but it should work now.
> 
> Update to newest version on PYPI (v0.2.2) and try again, thanks!
> 

Alright 👍
